import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToiletProvider } from '@/context/ToiletContext';
import TabBar from "@/components/tabbar/TabBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToiletProvider>
          <div style={{ paddingBottom: '72px' }}> {/* 탭바 높이에 맞게 조절 */}
            {children}
          </div>
        </ToiletProvider>
        <TabBar />

      </body>
    </html>
  );
}
